language: node_js
node_js:
  - "10"
  - "12"
  - "14"
os:
  - linux
  - osx
before_script:
  - npm install -g tape
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./docs
  on:
    branch: master
